name = "LMDB GUI Client"
icon = "icon.png"
version = "1.0.0"
author = "Your Name"
email = "your-email@example.com"
description = "A cross-platform GUI client for LMDB."
homepage = "https://example.com"
license = "MIT"
appID = "com.example.lmdbguiclient"

[build]
goos = ["darwin", "linux", "windows"]
goarch = ["amd64", "arm64"]

[output]
filename = "lmdb-gui-client"
directory = "build"

[resources]
include = ["icon.png", "theme/*", "config/*"]
