name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-win-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Cache fyne-cross
        uses: actions/cache@v4
        with:
          path: |
            ~/.fyne-cross
          key: ${{ runner.os }}-fyne-cross-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-fyne-cross-

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build for Windows
        run: fyne-cross windows --app-id com.example.lmdb-gui-client -arch=amd64 --icon icon.png

      - name: Build for Linux
        run: fyne-cross linux --app-id com.example.lmdb-gui-client -arch=amd64 --icon icon.png

      - name: Upload windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64
          path: fyne-cross/dist/windows-amd64

      - name: Upload linux build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: fyne-cross/dist/linux-amd64

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build for macOS
        run: |
          fyne package -os darwin -icon icon.png
          mkdir -p build/mac-arm64
          mv lmdb-gui-client.app build/mac-arm64/

      - name: Upload macOs build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm64
          path: build/mac-arm64

